"""
KAYO Uptime Monitor

Extracted from: SEVE-SaaS/kayo_monitor.py
Purpose: Continuous uptime monitoring with baseline comparison and anomaly detection.

Changes from original:
- Converted from CLI script to importable module
- Added type hints and structured output
- Replaced print(json.dumps(...)) with proper return values
- Added authorization requirement (target must be owned/authorized)
- Made async-compatible for service integration
"""
import time
import statistics
import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from urllib.request import urlopen, Request
from urllib.error import HTTPError, URLError

logger = logging.getLogger(__name__)


@dataclass
class ProbeResult:
    """Single probe result"""
    status_code: int
    latency_ms: int
    content_length: int = 0
    error: Optional[str] = None
    timestamp: float = field(default_factory=time.time)

    @property
    def is_healthy(self) -> bool:
        return self.status_code > 0 and self.status_code < 500


@dataclass
class MonitorAlert:
    """Alert generated by monitoring"""
    type: str  # endpoint_down, latency_spike, server_degraded, status_changed
    severity: str  # critical, high, medium, low
    message: str
    data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MonitorBaseline:
    """Established baseline for a monitored endpoint"""
    url: str
    avg_latency_ms: float
    typical_status: int
    established_at: float = field(default_factory=time.time)
    probe_count: int = 0


def probe(url: str, timeout: int = 8) -> ProbeResult:
    """
    Perform a single HTTP probe against a URL.

    Args:
        url: Target URL (must include scheme)
        timeout: Request timeout in seconds

    Returns:
        ProbeResult with status, latency, and any error
    """
    if not url.startswith("http"):
        url = "https://" + url

    start = time.time()
    try:
        req = Request(url, headers={"User-Agent": "KAYO-Monitor/1.0"})
        with urlopen(req, timeout=timeout) as resp:
            content = resp.read()
            return ProbeResult(
                status_code=resp.status,
                latency_ms=round((time.time() - start) * 1000),
                content_length=len(content),
            )
    except HTTPError as e:
        return ProbeResult(
            status_code=e.code,
            latency_ms=round((time.time() - start) * 1000),
        )
    except Exception as e:
        return ProbeResult(
            status_code=0,
            latency_ms=round((time.time() - start) * 1000),
            error=str(e),
        )


def establish_baseline(url: str, probe_count: int = 5, timeout: int = 8) -> Optional[MonitorBaseline]:
    """
    Establish a performance baseline for a URL.

    Performs multiple probes to determine normal latency and expected status.

    Args:
        url: Target URL
        probe_count: Number of probes for baseline
        timeout: Per-probe timeout

    Returns:
        MonitorBaseline or None if target is unreachable
    """
    latencies = []
    statuses = []

    for i in range(probe_count):
        result = probe(url, timeout)
        if result.status_code > 0:
            latencies.append(result.latency_ms)
            statuses.append(result.status_code)
        if i < probe_count - 1:
            time.sleep(2)  # Brief pause between baseline probes

    if not latencies:
        logger.warning(f"Could not establish baseline for {url}")
        return None

    return MonitorBaseline(
        url=url,
        avg_latency_ms=statistics.mean(latencies),
        typical_status=max(set(statuses), key=statuses.count),
        probe_count=probe_count,
    )


def evaluate_probe(
    result: ProbeResult,
    baseline: MonitorBaseline,
    consecutive_failures: int = 0,
) -> Optional[MonitorAlert]:
    """
    Evaluate a probe result against the baseline and generate alerts if needed.

    Args:
        result: Current probe result
        baseline: Established baseline
        consecutive_failures: Count of consecutive failed probes

    Returns:
        MonitorAlert if an alert condition is detected, None otherwise
    """
    is_down = result.status_code == 0 or result.status_code >= 500
    is_slow = result.latency_ms > baseline.avg_latency_ms * 3 and result.latency_ms > 1000
    is_degraded = result.status_code in [429, 502, 503, 504]
    status_changed = result.status_code != baseline.typical_status and result.status_code > 0

    if is_down and consecutive_failures >= 2:
        return MonitorAlert(
            type="endpoint_down",
            severity="critical",
            message=f"Endpoint unreachable for {consecutive_failures} consecutive probes",
            data={"consecutive_failures": consecutive_failures, "last_status": result.status_code},
        )

    if is_slow:
        slowdown = round(result.latency_ms / baseline.avg_latency_ms, 1)
        return MonitorAlert(
            type="latency_spike",
            severity="high",
            message=f"Response time {result.latency_ms}ms — {slowdown}x above baseline ({round(baseline.avg_latency_ms)}ms)",
            data={"latency_ms": result.latency_ms, "baseline_ms": round(baseline.avg_latency_ms), "slowdown_factor": slowdown},
        )

    if is_degraded:
        return MonitorAlert(
            type="server_degraded",
            severity="high",
            message=f"Server returned {result.status_code} — possible overload or rate limiting",
            data={"status_code": result.status_code},
        )

    if status_changed:
        return MonitorAlert(
            type="status_changed",
            severity="medium",
            message=f"Status changed from {baseline.typical_status} to {result.status_code}",
            data={"from_status": baseline.typical_status, "to_status": result.status_code},
        )

    return None
